//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSampleBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string Products { get; set; }
        public string Platform { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Process { get; set; }
        public string GitHubUrl { get; set; }
        public string CommitID { get; set; }
        public string IssueID { get; set; }
    }
}
